#!/bin/sh -e

### BEGIN INIT INFO
# Provides:          logelf-server
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: log to gelf to amqp bus 
# Description: This script will start logelf daemon.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="logelf daemon"
NAME=logelf
DAEMON="/usr/sbin/logelf.py"
PIDFILE=/var/run/logelf.pid

. /lib/lsb/init-functions

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

case "$1" in
start)
        echo -n "Starting logelf daemon:" "logelf "
        start_daemon $DAEMON $EXTRA_OPTS
        echo
        ;;
stop)
        echo -n "Stopping logelf daemon:" "logelf "
        killproc -p $PIDFILE $DAEMON
        echo
        ;;
restart)
        echo "Restarting logelf daemon:" "logelf "
        $0 stop
        $0 start
        ;;
status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
*)  log_action_msg "Usage: /etc/init.d/logelf {start|stop|status|restart}"
        exit 2
        ;;
esac
exit 0
